/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AiCallSchema extends BaseModel {
  static $columns = ['completionTokens', 'createdAt', 'error', 'feature', 'id', 'latencyMs', 'model', 'promptTokens', 'schoolId', 'status', 'updatedAt', 'userId'] as const
  $columns = AiCallSchema.$columns
  @column()
  declare completionTokens: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare error: string | null
  @column()
  declare feature: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare latencyMs: number
  @column()
  declare model: string
  @column()
  declare promptTokens: number
  @column()
  declare schoolId: number | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class AnnouncementSchema extends BaseModel {
  static $columns = ['authorUserId', 'body', 'createdAt', 'id', 'pinned', 'publishedAt', 'schoolId', 'targetRoles', 'targetRules', 'title', 'updatedAt'] as const
  $columns = AnnouncementSchema.$columns
  @column()
  declare authorUserId: number | null
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare pinned: boolean
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare schoolId: number
  @column()
  declare targetRoles: any | null
  @column()
  declare targetRules: any | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AssessmentSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'maxScore', 'name', 'orderIndex', 'schoolId', 'updatedAt', 'weight'] as const
  $columns = AssessmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare maxScore: number
  @column()
  declare name: string
  @column()
  declare orderIndex: number
  @column()
  declare schoolId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare weight: number
}

export class AssignmentSubmissionSchema extends BaseModel {
  static $columns = ['aiFeedback', 'aiFlags', 'aiRationale', 'aiSuggestedAt', 'aiSuggestedScore', 'assignmentId', 'attachmentUrl', 'content', 'createdAt', 'feedback', 'gradedAt', 'gradedByUserId', 'id', 'score', 'studentId', 'submittedAt', 'updatedAt'] as const
  $columns = AssignmentSubmissionSchema.$columns
  @column()
  declare aiFeedback: string | null
  @column()
  declare aiFlags: any | null
  @column()
  declare aiRationale: string | null
  @column.dateTime()
  declare aiSuggestedAt: DateTime | null
  @column()
  declare aiSuggestedScore: string | null
  @column()
  declare assignmentId: number
  @column()
  declare attachmentUrl: string | null
  @column()
  declare content: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare feedback: string | null
  @column.dateTime()
  declare gradedAt: DateTime | null
  @column()
  declare gradedByUserId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare score: string | null
  @column()
  declare studentId: number
  @column.dateTime()
  declare submittedAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AssignmentSchema extends BaseModel {
  static $columns = ['attachmentUrl', 'classId', 'createdAt', 'deadline', 'description', 'id', 'maxScore', 'published', 'rubric', 'schoolId', 'subjectId', 'teacherId', 'title', 'updatedAt'] as const
  $columns = AssignmentSchema.$columns
  @column()
  declare attachmentUrl: string | null
  @column()
  declare classId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deadline: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare maxScore: number
  @column()
  declare published: boolean
  @column()
  declare rubric: string | null
  @column()
  declare schoolId: number
  @column()
  declare subjectId: number
  @column()
  declare teacherId: number | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AssistantConversationSchema extends BaseModel {
  static $columns = ['channel', 'createdAt', 'id', 'schoolId', 'title', 'updatedAt', 'userId'] as const
  $columns = AssistantConversationSchema.$columns
  @column()
  declare channel: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare schoolId: number
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class AssistantMessageSchema extends BaseModel {
  static $columns = ['content', 'conversationId', 'createdAt', 'externalId', 'id', 'meta', 'role', 'updatedAt'] as const
  $columns = AssistantMessageSchema.$columns
  @column()
  declare content: string
  @column()
  declare conversationId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare externalId: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare meta: any | null
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AttendanceDaySchema extends BaseModel {
  static $columns = ['classId', 'createdAt', 'date', 'id', 'markedByUserId', 'note', 'schoolId', 'session', 'submitted', 'updatedAt'] as const
  $columns = AttendanceDaySchema.$columns
  @column()
  declare classId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare markedByUserId: number | null
  @column()
  declare note: string | null
  @column()
  declare schoolId: number
  @column()
  declare session: string
  @column()
  declare submitted: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AttendanceRecordSchema extends BaseModel {
  static $columns = ['attendanceDayId', 'createdAt', 'id', 'remark', 'status', 'studentId', 'updatedAt'] as const
  $columns = AttendanceRecordSchema.$columns
  @column()
  declare attendanceDayId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare remark: string | null
  @column()
  declare status: string
  @column()
  declare studentId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthorizedPickupSchema extends BaseModel {
  static $columns = ['active', 'addedByUserId', 'createdAt', 'fullName', 'id', 'phone', 'photoUrl', 'relationship', 'schoolId', 'studentId', 'updatedAt', 'validUntil'] as const
  $columns = AuthorizedPickupSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare addedByUserId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare phone: string | null
  @column()
  declare photoUrl: string | null
  @column()
  declare relationship: string | null
  @column()
  declare schoolId: number
  @column()
  declare studentId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.date()
  declare validUntil: DateTime | null
}

export class BankAccountSchema extends BaseModel {
  static $columns = ['accountNumber', 'accountType', 'bankName', 'createdAt', 'id', 'isActive', 'name', 'notes', 'openingBalanceKobo', 'schoolId', 'updatedAt'] as const
  $columns = BankAccountSchema.$columns
  @column()
  declare accountNumber: string
  @column()
  declare accountType: string | null
  @column()
  declare bankName: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare openingBalanceKobo: bigint | number
  @column()
  declare schoolId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CalendarEventSchema extends BaseModel {
  static $columns = ['allDay', 'color', 'createdAt', 'description', 'endsOn', 'eventType', 'id', 'schoolId', 'startsOn', 'title', 'updatedAt'] as const
  $columns = CalendarEventSchema.$columns
  @column()
  declare allDay: boolean
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column.date()
  declare endsOn: DateTime | null
  @column()
  declare eventType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare schoolId: number
  @column.date()
  declare startsOn: DateTime
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ClassSubjectSchema extends BaseModel {
  static $columns = ['classId', 'createdAt', 'id', 'subjectId', 'updatedAt'] as const
  $columns = ClassSubjectSchema.$columns
  @column()
  declare classId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare subjectId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ClassSchema extends BaseModel {
  static $columns = ['classTeacherId', 'createdAt', 'id', 'level', 'name', 'schoolId', 'updatedAt'] as const
  $columns = ClassSchema.$columns
  @column()
  declare classTeacherId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare level: string | null
  @column()
  declare name: string
  @column()
  declare schoolId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExamAnswerSchema extends BaseModel {
  static $columns = ['attemptId', 'createdAt', 'id', 'isCorrect', 'questionId', 'selectedIndex', 'updatedAt'] as const
  $columns = ExamAnswerSchema.$columns
  @column()
  declare attemptId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isCorrect: boolean
  @column()
  declare questionId: number
  @column()
  declare selectedIndex: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExamAttemptSchema extends BaseModel {
  static $columns = ['createdAt', 'examId', 'id', 'questionOrder', 'score', 'startedAt', 'status', 'studentId', 'submittedAt', 'totalMarks', 'updatedAt'] as const
  $columns = ExamAttemptSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare examId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare questionOrder: any
  @column()
  declare score: number | null
  @column.dateTime()
  declare startedAt: DateTime
  @column()
  declare status: string
  @column()
  declare studentId: number
  @column.dateTime()
  declare submittedAt: DateTime | null
  @column()
  declare totalMarks: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExamQuestionSchema extends BaseModel {
  static $columns = ['aiGenerated', 'correctIndex', 'createdAt', 'difficulty', 'examId', 'explanation', 'id', 'marks', 'options', 'orderIndex', 'prompt', 'topic', 'type', 'updatedAt'] as const
  $columns = ExamQuestionSchema.$columns
  @column()
  declare aiGenerated: boolean
  @column()
  declare correctIndex: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare difficulty: string | null
  @column()
  declare examId: number
  @column()
  declare explanation: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare marks: number
  @column()
  declare options: any
  @column()
  declare orderIndex: number
  @column()
  declare prompt: string
  @column()
  declare topic: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExamTutorNoteSchema extends BaseModel {
  static $columns = ['content', 'createdAt', 'id', 'questionId', 'selectedIndex', 'updatedAt'] as const
  $columns = ExamTutorNoteSchema.$columns
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare questionId: number
  @column()
  declare selectedIndex: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExamSchema extends BaseModel {
  static $columns = ['classId', 'closesAt', 'createdAt', 'durationMinutes', 'id', 'instructions', 'opensAt', 'resultsApprovedAt', 'resultsApprovedByUserId', 'reviewNote', 'reviewedAt', 'reviewedByUserId', 'schoolId', 'showScoreImmediately', 'shuffleQuestions', 'status', 'subjectId', 'teacherId', 'termId', 'title', 'updatedAt'] as const
  $columns = ExamSchema.$columns
  @column()
  declare classId: number
  @column.dateTime()
  declare closesAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare durationMinutes: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare instructions: string | null
  @column.dateTime()
  declare opensAt: DateTime | null
  @column.dateTime()
  declare resultsApprovedAt: DateTime | null
  @column()
  declare resultsApprovedByUserId: number | null
  @column()
  declare reviewNote: string | null
  @column.dateTime()
  declare reviewedAt: DateTime | null
  @column()
  declare reviewedByUserId: number | null
  @column()
  declare schoolId: number
  @column()
  declare showScoreImmediately: boolean
  @column()
  declare shuffleQuestions: boolean
  @column()
  declare status: string
  @column()
  declare subjectId: number
  @column()
  declare teacherId: number
  @column()
  declare termId: number | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExpenseSchema extends BaseModel {
  static $columns = ['amountKobo', 'category', 'createdAt', 'description', 'id', 'incurredOn', 'notes', 'receiptUrl', 'recordedByUserId', 'schoolId', 'updatedAt'] as const
  $columns = ExpenseSchema.$columns
  @column()
  declare amountKobo: bigint | number
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare incurredOn: DateTime
  @column()
  declare notes: string | null
  @column()
  declare receiptUrl: string | null
  @column()
  declare recordedByUserId: number | null
  @column()
  declare schoolId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FeeInvoiceItemSchema extends BaseModel {
  static $columns = ['amountKobo', 'createdAt', 'description', 'id', 'invoiceId', 'updatedAt'] as const
  $columns = FeeInvoiceItemSchema.$columns
  @column()
  declare amountKobo: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invoiceId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FeeInvoiceSchema extends BaseModel {
  static $columns = ['createdAt', 'dueOn', 'feeStructureId', 'id', 'invoiceNumber', 'issuedOn', 'notes', 'schoolId', 'status', 'studentId', 'termId', 'totalAmountKobo', 'updatedAt'] as const
  $columns = FeeInvoiceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dueOn: DateTime | null
  @column()
  declare feeStructureId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invoiceNumber: string
  @column.date()
  declare issuedOn: DateTime
  @column()
  declare notes: string | null
  @column()
  declare schoolId: number
  @column()
  declare status: string
  @column()
  declare studentId: number
  @column()
  declare termId: number
  @column()
  declare totalAmountKobo: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FeeItemSchema extends BaseModel {
  static $columns = ['amountKobo', 'createdAt', 'description', 'feeStructureId', 'id', 'isOptional', 'updatedAt'] as const
  $columns = FeeItemSchema.$columns
  @column()
  declare amountKobo: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column()
  declare feeStructureId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isOptional: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FeeStructureSchema extends BaseModel {
  static $columns = ['classId', 'classIds', 'createdAt', 'id', 'name', 'schoolId', 'termId', 'updatedAt'] as const
  $columns = FeeStructureSchema.$columns
  @column()
  declare classId: number | null
  @column()
  declare classIds: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare schoolId: number
  @column()
  declare termId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GateEventSchema extends BaseModel {
  static $columns = ['createdAt', 'day', 'device', 'direction', 'distanceM', 'id', 'lat', 'late', 'lng', 'method', 'note', 'occurredAt', 'personType', 'recordedByUserId', 'schoolId', 'studentId', 'updatedAt', 'userId'] as const
  $columns = GateEventSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare day: DateTime
  @column()
  declare device: string | null
  @column()
  declare direction: string
  @column()
  declare distanceM: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lat: string | null
  @column()
  declare late: boolean
  @column()
  declare lng: string | null
  @column()
  declare method: string
  @column()
  declare note: string | null
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare personType: string
  @column()
  declare recordedByUserId: number | null
  @column()
  declare schoolId: number
  @column()
  declare studentId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class GradeScaleSchema extends BaseModel {
  static $columns = ['createdAt', 'grade', 'id', 'minPercentage', 'orderIndex', 'remark', 'schoolId', 'updatedAt'] as const
  $columns = GradeScaleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare grade: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare minPercentage: string
  @column()
  declare orderIndex: number
  @column()
  declare remark: string
  @column()
  declare schoolId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class IntegrationSchema extends BaseModel {
  static $columns = ['config', 'createdAt', 'createdByUserId', 'hookToken', 'id', 'isDefault', 'kind', 'label', 'lastError', 'lastTestedAt', 'provider', 'schoolId', 'secrets', 'status', 'updatedAt'] as const
  $columns = IntegrationSchema.$columns
  @column()
  declare config: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column()
  declare hookToken: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDefault: boolean
  @column()
  declare kind: string
  @column()
  declare label: string | null
  @column()
  declare lastError: string | null
  @column.dateTime()
  declare lastTestedAt: DateTime | null
  @column()
  declare provider: string
  @column()
  declare schoolId: number
  @column()
  declare secrets: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InventoryItemSchema extends BaseModel {
  static $columns = ['active', 'category', 'createdAt', 'id', 'name', 'notes', 'quantity', 'reorderLevel', 'schoolId', 'sku', 'store', 'unit', 'unitCostKobo', 'updatedAt'] as const
  $columns = InventoryItemSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare quantity: number
  @column()
  declare reorderLevel: number
  @column()
  declare schoolId: number
  @column()
  declare sku: string | null
  @column()
  declare store: string | null
  @column()
  declare unit: string
  @column()
  declare unitCostKobo: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LeaveRequestSchema extends BaseModel {
  static $columns = ['attachmentUrl', 'createdAt', 'decidedAt', 'decidedByUserId', 'decisionNote', 'endsOn', 'id', 'kind', 'reason', 'schoolId', 'startsOn', 'status', 'updatedAt', 'userId'] as const
  $columns = LeaveRequestSchema.$columns
  @column()
  declare attachmentUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare decidedAt: DateTime | null
  @column()
  declare decidedByUserId: number | null
  @column()
  declare decisionNote: string | null
  @column.date()
  declare endsOn: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare reason: string | null
  @column()
  declare schoolId: number
  @column.date()
  declare startsOn: DateTime
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class MessageCampaignSchema extends BaseModel {
  static $columns = ['audience', 'body', 'channels', 'createdAt', 'createdByUserId', 'event', 'id', 'schoolId', 'source', 'status', 'subject', 'title', 'total', 'updatedAt'] as const
  $columns = MessageCampaignSchema.$columns
  @column()
  declare audience: any | null
  @column()
  declare body: string
  @column()
  declare channels: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column()
  declare event: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare schoolId: number
  @column()
  declare source: string
  @column()
  declare status: string
  @column()
  declare subject: string | null
  @column()
  declare title: string
  @column()
  declare total: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MessageDeliverySchema extends BaseModel {
  static $columns = ['body', 'campaignId', 'channel', 'createdAt', 'deliveredAt', 'error', 'id', 'integrationId', 'provider', 'providerMessageId', 'recipientName', 'recipientUserId', 'schoolId', 'sentAt', 'status', 'studentId', 'subject', 'toAddress', 'updatedAt'] as const
  $columns = MessageDeliverySchema.$columns
  @column()
  declare body: string
  @column()
  declare campaignId: number | null
  @column()
  declare channel: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deliveredAt: DateTime | null
  @column()
  declare error: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare integrationId: number | null
  @column()
  declare provider: string | null
  @column()
  declare providerMessageId: string | null
  @column()
  declare recipientName: string | null
  @column()
  declare recipientUserId: number | null
  @column()
  declare schoolId: number
  @column.dateTime()
  declare sentAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare studentId: number | null
  @column()
  declare subject: string | null
  @column()
  declare toAddress: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MessageTemplateSchema extends BaseModel {
  static $columns = ['body', 'channel', 'createdAt', 'id', 'name', 'schoolId', 'subject', 'updatedAt'] as const
  $columns = MessageTemplateSchema.$columns
  @column()
  declare body: string
  @column()
  declare channel: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare schoolId: number
  @column()
  declare subject: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NotificationDispatchSchema extends BaseModel {
  static $columns = ['createdAt', 'forDate', 'id', 'kind', 'slotId', 'userId'] as const
  $columns = NotificationDispatchSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare forDate: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare slotId: number
  @column()
  declare userId: number
}

export class NotificationSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'data', 'id', 'kind', 'readAt', 'schoolId', 'title', 'updatedAt', 'userId'] as const
  $columns = NotificationSchema.$columns
  @column()
  declare body: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare data: any | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare schoolId: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class ParentStudentSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isPrimary', 'parentUserId', 'relationship', 'studentId', 'updatedAt'] as const
  $columns = ParentStudentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPrimary: boolean
  @column()
  declare parentUserId: number
  @column()
  declare relationship: string | null
  @column()
  declare studentId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PaymentSchema extends BaseModel {
  static $columns = ['amountKobo', 'createdAt', 'id', 'invoiceId', 'method', 'notes', 'paidAt', 'recordedByUserId', 'reference', 'schoolId', 'studentId', 'updatedAt'] as const
  $columns = PaymentSchema.$columns
  @column()
  declare amountKobo: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invoiceId: number
  @column()
  declare method: string
  @column()
  declare notes: string | null
  @column.dateTime()
  declare paidAt: DateTime
  @column()
  declare recordedByUserId: number | null
  @column()
  declare reference: string | null
  @column()
  declare schoolId: number
  @column()
  declare studentId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PayrollProfileSchema extends BaseModel {
  static $columns = ['accountName', 'accountNumber', 'active', 'allowances', 'bankName', 'baseSalaryKobo', 'createdAt', 'deductions', 'id', 'pensionPercent', 'schoolId', 'taxKobo', 'updatedAt', 'userId'] as const
  $columns = PayrollProfileSchema.$columns
  @column()
  declare accountName: string | null
  @column()
  declare accountNumber: string | null
  @column()
  declare active: boolean
  @column()
  declare allowances: any | null
  @column()
  declare bankName: string | null
  @column()
  declare baseSalaryKobo: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deductions: any | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare pensionPercent: string
  @column()
  declare schoolId: number
  @column()
  declare taxKobo: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class PayrollRunSchema extends BaseModel {
  static $columns = ['approvedAt', 'approvedByUserId', 'createdAt', 'createdByUserId', 'deductionsKobo', 'grossKobo', 'id', 'netKobo', 'notes', 'paidAt', 'period', 'schoolId', 'status', 'updatedAt'] as const
  $columns = PayrollRunSchema.$columns
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column()
  declare approvedByUserId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column()
  declare deductionsKobo: bigint | number
  @column()
  declare grossKobo: bigint | number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare netKobo: bigint | number
  @column()
  declare notes: string | null
  @column.dateTime()
  declare paidAt: DateTime | null
  @column()
  declare period: string
  @column()
  declare schoolId: number
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PayslipSchema extends BaseModel {
  static $columns = ['accountName', 'accountNumber', 'bankName', 'createdAt', 'deductionsKobo', 'grossKobo', 'id', 'lines', 'netKobo', 'runId', 'schoolId', 'staffName', 'updatedAt', 'userId'] as const
  $columns = PayslipSchema.$columns
  @column()
  declare accountName: string | null
  @column()
  declare accountNumber: string | null
  @column()
  declare bankName: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deductionsKobo: bigint | number
  @column()
  declare grossKobo: bigint | number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lines: any
  @column()
  declare netKobo: bigint | number
  @column()
  declare runId: number
  @column()
  declare schoolId: number
  @column()
  declare staffName: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class PermissionOverrideSchema extends BaseModel {
  static $columns = ['action', 'createdAt', 'effect', 'grantedByUserId', 'id', 'resource', 'schoolId', 'updatedAt', 'userId'] as const
  $columns = PermissionOverrideSchema.$columns
  @column()
  declare action: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare effect: string
  @column()
  declare grantedByUserId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare resource: string
  @column()
  declare schoolId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class PickupLogSchema extends BaseModel {
  static $columns = ['authorizedPickupId', 'collectorName', 'collectorType', 'collectorUserId', 'createdAt', 'day', 'id', 'method', 'note', 'occurredAt', 'outcome', 'recordedByUserId', 'schoolId', 'studentId', 'updatedAt'] as const
  $columns = PickupLogSchema.$columns
  @column()
  declare authorizedPickupId: number | null
  @column()
  declare collectorName: string | null
  @column()
  declare collectorType: string | null
  @column()
  declare collectorUserId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare day: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare method: string
  @column()
  declare note: string | null
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare outcome: string
  @column()
  declare recordedByUserId: number | null
  @column()
  declare schoolId: number
  @column()
  declare studentId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PracticeSetSchema extends BaseModel {
  static $columns = ['answers', 'completedAt', 'createdAt', 'difficulty', 'id', 'questions', 'schoolId', 'score', 'studentId', 'subjectId', 'topic', 'updatedAt'] as const
  $columns = PracticeSetSchema.$columns
  @column()
  declare answers: any
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare difficulty: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare questions: any
  @column()
  declare schoolId: number
  @column()
  declare score: number
  @column()
  declare studentId: number
  @column()
  declare subjectId: number
  @column()
  declare topic: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PurchaseSchema extends BaseModel {
  static $columns = ['createdAt', 'expenseId', 'id', 'note', 'purchasedOn', 'recordedByUserId', 'reference', 'schoolId', 'supplierId', 'totalKobo', 'updatedAt'] as const
  $columns = PurchaseSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare expenseId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare note: string | null
  @column.date()
  declare purchasedOn: DateTime
  @column()
  declare recordedByUserId: number | null
  @column()
  declare reference: string | null
  @column()
  declare schoolId: number
  @column()
  declare supplierId: number | null
  @column()
  declare totalKobo: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ReportApprovalSchema extends BaseModel {
  static $columns = ['approvedAt', 'approvedByUserId', 'createdAt', 'id', 'studentId', 'termId', 'updatedAt'] as const
  $columns = ReportApprovalSchema.$columns
  @column.dateTime()
  declare approvedAt: DateTime
  @column()
  declare approvedByUserId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare studentId: number
  @column()
  declare termId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ReportCardCommentSchema extends BaseModel {
  static $columns = ['classTeacherComment', 'createdAt', 'id', 'principalComment', 'studentId', 'termId', 'updatedAt'] as const
  $columns = ReportCardCommentSchema.$columns
  @column()
  declare classTeacherComment: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare principalComment: string | null
  @column()
  declare studentId: number
  @column()
  declare termId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SchoolSchema extends BaseModel {
  static $columns = ['badgeUrl', 'createdAt', 'id', 'letterheadUrl', 'name', 'settings', 'signatureUrl', 'slug', 'subdomain', 'theme', 'updatedAt'] as const
  $columns = SchoolSchema.$columns
  @column()
  declare badgeUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare letterheadUrl: string | null
  @column()
  declare name: string
  @column()
  declare settings: any | null
  @column()
  declare signatureUrl: string | null
  @column()
  declare slug: string
  @column()
  declare subdomain: string | null
  @column()
  declare theme: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ScoreSchema extends BaseModel {
  static $columns = ['assessmentId', 'createdAt', 'enteredByUserId', 'id', 'score', 'studentId', 'subjectId', 'termId', 'updatedAt'] as const
  $columns = ScoreSchema.$columns
  @column()
  declare assessmentId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enteredByUserId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare score: string
  @column()
  declare studentId: number
  @column()
  declare subjectId: number
  @column()
  declare termId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StockMovementSchema extends BaseModel {
  static $columns = ['balanceAfter', 'createdAt', 'id', 'issuedTo', 'itemId', 'note', 'occurredAt', 'purchaseId', 'quantity', 'recordedByUserId', 'schoolId', 'type', 'unitCostKobo', 'updatedAt'] as const
  $columns = StockMovementSchema.$columns
  @column()
  declare balanceAfter: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare issuedTo: string | null
  @column()
  declare itemId: number
  @column()
  declare note: string | null
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare purchaseId: number | null
  @column()
  declare quantity: number
  @column()
  declare recordedByUserId: number | null
  @column()
  declare schoolId: number
  @column()
  declare type: string
  @column()
  declare unitCostKobo: bigint | number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StudentRiskFlagSchema extends BaseModel {
  static $columns = ['classId', 'computedAt', 'createdAt', 'id', 'level', 'reviewNote', 'reviewedAt', 'reviewedByUserId', 'schoolId', 'score', 'signalHash', 'signals', 'status', 'studentId', 'suggestedAction', 'summary', 'updatedAt'] as const
  $columns = StudentRiskFlagSchema.$columns
  @column()
  declare classId: number | null
  @column.dateTime()
  declare computedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare level: string
  @column()
  declare reviewNote: string | null
  @column.dateTime()
  declare reviewedAt: DateTime | null
  @column()
  declare reviewedByUserId: number | null
  @column()
  declare schoolId: number
  @column()
  declare score: number
  @column()
  declare signalHash: string
  @column()
  declare signals: any
  @column()
  declare status: string
  @column()
  declare studentId: number
  @column()
  declare suggestedAction: string | null
  @column()
  declare summary: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StudentSchema extends BaseModel {
  static $columns = ['address', 'admissionNumber', 'admissionYear', 'allergies', 'bloodGroup', 'classId', 'createdAt', 'dateOfBirth', 'email', 'emergencyContactName', 'emergencyContactPhone', 'firstName', 'gender', 'homeLanguage', 'id', 'isArchived', 'lastName', 'medicalNotes', 'middleName', 'phone', 'photoUrl', 'previousSchool', 'religion', 'schoolId', 'updatedAt', 'userId'] as const
  $columns = StudentSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare admissionNumber: string
  @column()
  declare admissionYear: number | null
  @column()
  declare allergies: string | null
  @column()
  declare bloodGroup: string | null
  @column()
  declare classId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dateOfBirth: DateTime | null
  @column()
  declare email: string | null
  @column()
  declare emergencyContactName: string | null
  @column()
  declare emergencyContactPhone: string | null
  @column()
  declare firstName: string
  @column()
  declare gender: string | null
  @column()
  declare homeLanguage: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isArchived: boolean
  @column()
  declare lastName: string
  @column()
  declare medicalNotes: string | null
  @column()
  declare middleName: string | null
  @column()
  declare phone: string | null
  @column()
  declare photoUrl: string | null
  @column()
  declare previousSchool: string | null
  @column()
  declare religion: string | null
  @column()
  declare schoolId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class SubjectSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'id', 'name', 'schoolId', 'updatedAt'] as const
  $columns = SubjectSchema.$columns
  @column()
  declare code: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare schoolId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SupplierSchema extends BaseModel {
  static $columns = ['address', 'contactName', 'createdAt', 'email', 'id', 'name', 'notes', 'phone', 'schoolId', 'updatedAt'] as const
  $columns = SupplierSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare contactName: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare phone: string | null
  @column()
  declare schoolId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TeacherSubjectSchema extends BaseModel {
  static $columns = ['classId', 'createdAt', 'id', 'subjectId', 'updatedAt', 'userId'] as const
  $columns = TeacherSubjectSchema.$columns
  @column()
  declare classId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare subjectId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class TermSchema extends BaseModel {
  static $columns = ['createdAt', 'endsOn', 'id', 'isCurrent', 'name', 'schoolId', 'session', 'startsOn', 'updatedAt'] as const
  $columns = TermSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare endsOn: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isCurrent: boolean
  @column()
  declare name: string
  @column()
  declare schoolId: number
  @column()
  declare session: string
  @column.date()
  declare startsOn: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TimetablePeriodSchema extends BaseModel {
  static $columns = ['createdAt', 'endTime', 'id', 'isBreak', 'name', 'orderIndex', 'schoolId', 'startTime', 'updatedAt'] as const
  $columns = TimetablePeriodSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare endTime: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isBreak: boolean
  @column()
  declare name: string
  @column()
  declare orderIndex: number
  @column()
  declare schoolId: number
  @column()
  declare startTime: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TimetableSlotExceptionSchema extends BaseModel {
  static $columns = ['createdAt', 'date', 'id', 'isCancelled', 'notes', 'slotId', 'subjectId', 'teacherId', 'updatedAt'] as const
  $columns = TimetableSlotExceptionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isCancelled: boolean
  @column()
  declare notes: string | null
  @column()
  declare slotId: number
  @column()
  declare subjectId: number | null
  @column()
  declare teacherId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TimetableSlotSchema extends BaseModel {
  static $columns = ['classId', 'createdAt', 'dayOfWeek', 'id', 'notes', 'periodId', 'schoolId', 'subjectId', 'teacherId', 'updatedAt'] as const
  $columns = TimetableSlotSchema.$columns
  @column()
  declare classId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dayOfWeek: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notes: string | null
  @column()
  declare periodId: number
  @column()
  declare schoolId: number
  @column()
  declare subjectId: number | null
  @column()
  declare teacherId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchoolRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'role', 'schoolId', 'updatedAt', 'userId'] as const
  $columns = UserSchoolRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare role: string
  @column()
  declare schoolId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'lastLoginAt', 'mustChangePassword', 'password', 'phone', 'surname', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column()
  declare mustChangePassword: boolean
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phone: string | null
  @column()
  declare surname: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VisitorSchema extends BaseModel {
  static $columns = ['checkedInAt', 'checkedOutAt', 'createdAt', 'fullName', 'hostUserId', 'id', 'idNumber', 'idType', 'notes', 'phone', 'purpose', 'recordedByUserId', 'schoolId', 'updatedAt'] as const
  $columns = VisitorSchema.$columns
  @column.dateTime()
  declare checkedInAt: DateTime
  @column.dateTime()
  declare checkedOutAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fullName: string
  @column()
  declare hostUserId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idNumber: string | null
  @column()
  declare idType: string | null
  @column()
  declare notes: string | null
  @column()
  declare phone: string | null
  @column()
  declare purpose: string | null
  @column()
  declare recordedByUserId: number | null
  @column()
  declare schoolId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WhatsappLinkSchema extends BaseModel {
  static $columns = ['code', 'codeExpiresAt', 'createdAt', 'id', 'linkedAt', 'phone', 'schoolId', 'updatedAt', 'userId'] as const
  $columns = WhatsappLinkSchema.$columns
  @column()
  declare code: string | null
  @column.dateTime()
  declare codeExpiresAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare linkedAt: DateTime | null
  @column()
  declare phone: string | null
  @column()
  declare schoolId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}
